// Copyright 2017-2021 @bifrost-finance/types authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Auto-generated by @polkadot/dev, do not edit

export const packageInfo = { name: '@zenlink-types/bifrost', version: '1.7.3' };
